export interface Achievement {
  id: string;
  title: string;
  description: string;
  category: 'consistency' | 'goals' | 'social' | 'learning' | 'wellness' | 'special';
  icon: string;
  tier: 'bronze' | 'silver' | 'gold';
  requirement: number;
  currentProgress: number;
  isUnlocked: boolean;
  unlockedAt?: string;
  color: string;
  gradient: string[];
}

export interface AchievementCategory {
  id: string;
  title: string;
  description: string;
  icon: string;
  color: string;
  achievements: Achievement[];
}

export const ACHIEVEMENT_DEFINITIONS: Achievement[] = [
  // Early Bird
  {
    id: 'early-bird-bronze',
    title: 'Early Bird',
    description: 'Complete 5 tasks before their deadlines',
    category: 'goals',
    icon: '🌅',
    tier: 'bronze',
    requirement: 5,
    currentProgress: 0,
    isUnlocked: false,
    color: '#8B6D5C',
    gradient: ['#8B6D5C', '#D9A441'],
  },
  {
    id: 'early-bird-silver',
    title: 'Dawn Warrior',
    description: 'Complete 15 tasks before their deadlines',
    category: 'goals',
    icon: '🌅',
    tier: 'silver',
    requirement: 15,
    currentProgress: 0,
    isUnlocked: false,
    color: '#A3C4D9',
    gradient: ['#A3C4D9', '#F5F1E9'],
  },
  {
    id: 'early-bird-gold',
    title: 'Sunrise Master',
    description: 'Complete 50 tasks before their deadlines',
    category: 'goals',
    icon: '🌅',
    tier: 'gold',
    requirement: 50,
    currentProgress: 0,
    isUnlocked: false,
    color: '#D9A441',
    gradient: ['#D9A441', '#A8C686'],
  },

  // Consistency Champion
  {
    id: 'consistency-bronze',
    title: 'Consistency Champion',
    description: 'Maintain a 7-day activity streak',
    category: 'consistency',
    icon: '🔥',
    tier: 'bronze',
    requirement: 7,
    currentProgress: 0,
    isUnlocked: false,
    color: '#CD7F32',
    gradient: ['#CD7F32', '#B8860B'],
  },
  {
    id: 'consistency-silver',
    title: 'Streak Warrior',
    description: 'Maintain a 30-day activity streak',
    category: 'consistency',
    icon: '🔥',
    tier: 'silver',
    requirement: 30,
    currentProgress: 0,
    isUnlocked: false,
    color: '#C0C0C0',
    gradient: ['#C0C0C0', '#A8A8A8'],
  },
  {
    id: 'consistency-gold',
    title: 'Unstoppable Force',
    description: 'Maintain a 100-day activity streak',
    category: 'consistency',
    icon: '🔥',
    tier: 'gold',
    requirement: 100,
    currentProgress: 0,
    isUnlocked: false,
    color: '#FFD700',
    gradient: ['#FFD700', '#FFA500'],
  },

  // Goal Crusher
  {
    id: 'goal-crusher-bronze',
    title: 'Goal Crusher',
    description: 'Achieve 3 set targets',
    category: 'goals',
    icon: '🎯',
    tier: 'bronze',
    requirement: 3,
    currentProgress: 0,
    isUnlocked: false,
    color: '#CD7F32',
    gradient: ['#CD7F32', '#B8860B'],
  },
  {
    id: 'goal-crusher-silver',
    title: 'Target Master',
    description: 'Achieve 10 set targets',
    category: 'goals',
    icon: '🎯',
    tier: 'silver',
    requirement: 10,
    currentProgress: 0,
    isUnlocked: false,
    color: '#C0C0C0',
    gradient: ['#C0C0C0', '#A8A8A8'],
  },
  {
    id: 'goal-crusher-gold',
    title: 'Achievement Legend',
    description: 'Achieve 25 set targets',
    category: 'goals',
    icon: '🎯',
    tier: 'gold',
    requirement: 25,
    currentProgress: 0,
    isUnlocked: false,
    color: '#FFD700',
    gradient: ['#FFD700', '#FFA500'],
  },

  // Team Player
  {
    id: 'team-player-bronze',
    title: 'Team Player',
    description: 'Contribute positively to 5 group activities',
    category: 'social',
    icon: '🤝',
    tier: 'bronze',
    requirement: 5,
    currentProgress: 0,
    isUnlocked: false,
    color: '#CD7F32',
    gradient: ['#CD7F32', '#B8860B'],
  },
  {
    id: 'team-player-silver',
    title: 'Collaboration Expert',
    description: 'Contribute positively to 15 group activities',
    category: 'social',
    icon: '🤝',
    tier: 'silver',
    requirement: 15,
    currentProgress: 0,
    isUnlocked: false,
    color: '#C0C0C0',
    gradient: ['#C0C0C0', '#A8A8A8'],
  },
  {
    id: 'team-player-gold',
    title: 'Unity Champion',
    description: 'Contribute positively to 50 group activities',
    category: 'social',
    icon: '🤝',
    tier: 'gold',
    requirement: 50,
    currentProgress: 0,
    isUnlocked: false,
    color: '#FFD700',
    gradient: ['#FFD700', '#FFA500'],
  },

  // Innovation Star
  {
    id: 'innovation-bronze',
    title: 'Innovation Star',
    description: 'Propose 3 creative solutions',
    category: 'learning',
    icon: '💡',
    tier: 'bronze',
    requirement: 3,
    currentProgress: 0,
    isUnlocked: false,
    color: '#CD7F32',
    gradient: ['#CD7F32', '#B8860B'],
  },
  {
    id: 'innovation-silver',
    title: 'Creative Genius',
    description: 'Propose 10 creative solutions',
    category: 'learning',
    icon: '💡',
    tier: 'silver',
    requirement: 10,
    currentProgress: 0,
    isUnlocked: false,
    color: '#C0C0C0',
    gradient: ['#C0C0C0', '#A8A8A8'],
  },
  {
    id: 'innovation-gold',
    title: 'Visionary Leader',
    description: 'Propose 25 creative solutions',
    category: 'learning',
    icon: '💡',
    tier: 'gold',
    requirement: 25,
    currentProgress: 0,
    isUnlocked: false,
    color: '#FFD700',
    gradient: ['#FFD700', '#FFA500'],
  },

  // Progress Master
  {
    id: 'progress-bronze',
    title: 'Progress Master',
    description: 'Show significant improvement in 3 areas',
    category: 'wellness',
    icon: '📈',
    tier: 'bronze',
    requirement: 3,
    currentProgress: 0,
    isUnlocked: false,
    color: '#CD7F32',
    gradient: ['#CD7F32', '#B8860B'],
  },
  {
    id: 'progress-silver',
    title: 'Growth Expert',
    description: 'Show significant improvement in 8 areas',
    category: 'wellness',
    icon: '📈',
    tier: 'silver',
    requirement: 8,
    currentProgress: 0,
    isUnlocked: false,
    color: '#C0C0C0',
    gradient: ['#C0C0C0', '#A8A8A8'],
  },
  {
    id: 'progress-gold',
    title: 'Transformation Guru',
    description: 'Show significant improvement in 15 areas',
    category: 'wellness',
    icon: '📈',
    tier: 'gold',
    requirement: 15,
    currentProgress: 0,
    isUnlocked: false,
    color: '#FFD700',
    gradient: ['#FFD700', '#FFA500'],
  },

  // Feedback Pro
  {
    id: 'feedback-bronze',
    title: 'Feedback Pro',
    description: 'Provide constructive feedback 5 times',
    category: 'social',
    icon: '💬',
    tier: 'bronze',
    requirement: 5,
    currentProgress: 0,
    isUnlocked: false,
    color: '#CD7F32',
    gradient: ['#CD7F32', '#B8860B'],
  },
  {
    id: 'feedback-silver',
    title: 'Mentor',
    description: 'Provide constructive feedback 20 times',
    category: 'social',
    icon: '💬',
    tier: 'silver',
    requirement: 20,
    currentProgress: 0,
    isUnlocked: false,
    color: '#C0C0C0',
    gradient: ['#C0C0C0', '#A8A8A8'],
  },
  {
    id: 'feedback-gold',
    title: 'Wisdom Keeper',
    description: 'Provide constructive feedback 50 times',
    category: 'social',
    icon: '💬',
    tier: 'gold',
    requirement: 50,
    currentProgress: 0,
    isUnlocked: false,
    color: '#FFD700',
    gradient: ['#FFD700', '#FFA500'],
  },

  // Challenge Accepted
  {
    id: 'challenge-bronze',
    title: 'Challenge Accepted',
    description: 'Complete 3 difficult tasks',
    category: 'goals',
    icon: '⚡',
    tier: 'bronze',
    requirement: 3,
    currentProgress: 0,
    isUnlocked: false,
    color: '#CD7F32',
    gradient: ['#CD7F32', '#B8860B'],
  },
  {
    id: 'challenge-silver',
    title: 'Obstacle Crusher',
    description: 'Complete 10 difficult tasks',
    category: 'goals',
    icon: '⚡',
    tier: 'silver',
    requirement: 10,
    currentProgress: 0,
    isUnlocked: false,
    color: '#C0C0C0',
    gradient: ['#C0C0C0', '#A8A8A8'],
  },
  {
    id: 'challenge-gold',
    title: 'Impossible Achiever',
    description: 'Complete 25 difficult tasks',
    category: 'goals',
    icon: '⚡',
    tier: 'gold',
    requirement: 25,
    currentProgress: 0,
    isUnlocked: false,
    color: '#FFD700',
    gradient: ['#FFD700', '#FFA500'],
  },

  // Perfect Attendance
  {
    id: 'attendance-bronze',
    title: 'Perfect Attendance',
    description: 'Maintain 100% attendance for 1 week',
    category: 'consistency',
    icon: '✅',
    tier: 'bronze',
    requirement: 7,
    currentProgress: 0,
    isUnlocked: false,
    color: '#CD7F32',
    gradient: ['#CD7F32', '#B8860B'],
  },
  {
    id: 'attendance-silver',
    title: 'Reliability Star',
    description: 'Maintain 100% attendance for 1 month',
    category: 'consistency',
    icon: '✅',
    tier: 'silver',
    requirement: 30,
    currentProgress: 0,
    isUnlocked: false,
    color: '#C0C0C0',
    gradient: ['#C0C0C0', '#A8A8A8'],
  },
  {
    id: 'attendance-gold',
    title: 'Dedication Legend',
    description: 'Maintain 100% attendance for 3 months',
    category: 'consistency',
    icon: '✅',
    tier: 'gold',
    requirement: 90,
    currentProgress: 0,
    isUnlocked: false,
    color: '#FFD700',
    gradient: ['#FFD700', '#FFA500'],
  },

  // Knowledge Seeker
  {
    id: 'knowledge-bronze',
    title: 'Knowledge Seeker',
    description: 'Participate in 5 learning activities',
    category: 'learning',
    icon: '📚',
    tier: 'bronze',
    requirement: 5,
    currentProgress: 0,
    isUnlocked: false,
    color: '#CD7F32',
    gradient: ['#CD7F32', '#B8860B'],
  },
  {
    id: 'knowledge-silver',
    title: 'Scholar',
    description: 'Participate in 20 learning activities',
    category: 'learning',
    icon: '📚',
    tier: 'silver',
    requirement: 20,
    currentProgress: 0,
    isUnlocked: false,
    color: '#C0C0C0',
    gradient: ['#C0C0C0', '#A8A8A8'],
  },
  {
    id: 'knowledge-gold',
    title: 'Master Learner',
    description: 'Participate in 50 learning activities',
    category: 'learning',
    icon: '📚',
    tier: 'gold',
    requirement: 50,
    currentProgress: 0,
    isUnlocked: false,
    color: '#FFD700',
    gradient: ['#FFD700', '#FFA500'],
  },
];