import { GuidedSession } from '@/components/GuidedSessionModal';

export const GUIDED_SESSIONS: GuidedSession[] = [
  {
    id: 'breathing-5min',
    title: '5-Minute Breathing',
    description: 'Quick stress relief breathing exercise',
    duration: 300, // 5 minutes
    type: 'breathing',
    backgroundSound: 'ocean',
    gradientColors: ['#A8E6CF', '#81ECEC'],
    instructions: [
      { time: 0, text: 'Get comfortable and close your eyes if you wish', duration: 10 },
      { time: 10, text: 'Take a deep breath in through your nose for 4 counts', duration: 15 },
      { time: 25, text: 'Hold your breath for 4 counts', duration: 15 },
      { time: 40, text: 'Exhale slowly through your mouth for 6 counts', duration: 15 },
      { time: 55, text: 'Continue this rhythm: In for 4, hold for 4, out for 6', duration: 60 },
      { time: 115, text: 'Feel your body relaxing with each breath', duration: 30 },
      { time: 145, text: 'Notice any tension melting away', duration: 30 },
      { time: 175, text: 'You\'re doing great, keep breathing steadily', duration: 30 },
      { time: 205, text: 'Focus only on your breath, let thoughts pass by', duration: 30 },
      { time: 235, text: 'Feel the calm spreading through your body', duration: 30 },
      { time: 265, text: 'Take these last few breaths mindfully', duration: 20 },
      { time: 285, text: 'When ready, slowly open your eyes', duration: 15 },
    ],
  },
  {
    id: 'commute-meditation',
    title: 'Commute Meditation',
    description: 'Mindfulness for your journey',
    duration: 900, // 15 minutes
    type: 'meditation',
    backgroundSound: 'forest',
    gradientColors: ['#DDA0DD', '#FFB6C1'],
    instructions: [
      { time: 0, text: 'Welcome to your commute meditation', duration: 10 },
      { time: 10, text: 'Sit comfortably and take three deep breaths', duration: 20 },
      { time: 30, text: 'Notice the sounds around you without judgment', duration: 30 },
      { time: 60, text: 'Feel your body in contact with your seat', duration: 30 },
      { time: 90, text: 'Observe the movement and rhythm of your journey', duration: 60 },
      { time: 150, text: 'When your mind wanders, gently return to the present', duration: 60 },
      { time: 210, text: 'Notice your breathing, natural and easy', duration: 60 },
      { time: 270, text: 'Appreciate this time you\'re giving yourself', duration: 60 },
      { time: 330, text: 'Feel gratitude for this moment of peace', duration: 60 },
      { time: 390, text: 'Continue to breathe mindfully', duration: 120 },
      { time: 510, text: 'Notice how calm and centered you feel', duration: 60 },
      { time: 570, text: 'Carry this peace with you throughout your day', duration: 60 },
      { time: 630, text: 'You\'re creating positive change in your life', duration: 60 },
      { time: 690, text: 'Take a moment to appreciate your commitment', duration: 60 },
      { time: 750, text: 'Feel ready and refreshed for what lies ahead', duration: 60 },
      { time: 810, text: 'When you\'re ready, slowly return your attention outward', duration: 30 },
      { time: 840, text: 'Take three deep breaths to complete your practice', duration: 30 },
      { time: 870, text: 'Well done. You\'ve given yourself a wonderful gift', duration: 30 },
    ],
  },
  {
    id: 'morning-motivation-quotes',
    title: 'Morning Motivation',
    description: 'Start your day with positivity and inspiring quotes',
    duration: 480, // 8 minutes
    type: 'motivation',
    backgroundSound: 'silence',
    gradientColors: ['#FFD93D', '#A8E6CF'],
    instructions: [
      { time: 0, text: 'Welcome to your morning motivation session', duration: 10 },
      { time: 10, text: 'Take a deep breath and prepare to be inspired', duration: 15 },
      { time: 25, text: 'Swipe through motivational quotes at your own pace', duration: 20 },
      { time: 45, text: 'Let each quote resonate with your heart', duration: 30 },
      { time: 75, text: 'Feel the positive energy building within you', duration: 60 },
      { time: 135, text: 'You have unlimited potential', duration: 30 },
      { time: 165, text: 'Today is a new opportunity to grow', duration: 30 },
      { time: 195, text: 'Believe in yourself and your dreams', duration: 30 },
      { time: 225, text: 'You are capable of amazing things', duration: 60 },
      { time: 285, text: 'Carry this inspiration throughout your day', duration: 60 },
      { time: 345, text: 'You are ready to make today extraordinary', duration: 60 },
      { time: 405, text: 'Take three deep breaths of confidence', duration: 30 },
      { time: 435, text: 'Step into your day with purpose and joy', duration: 30 },
      { time: 465, text: 'You\'ve got this!', duration: 15 },
    ],
  },
  {
    id: 'focus-enhancement',
    title: 'Focus Enhancement',
    description: 'Improve concentration and clarity',
    duration: 600, // 10 minutes
    type: 'focus',
    backgroundSound: 'wind',
    gradientColors: ['#FFB6C1', '#A8E6CF'],
    instructions: [
      { time: 0, text: 'Prepare to enhance your focus and mental clarity', duration: 10 },
      { time: 10, text: 'Sit up straight and take a deep, energizing breath', duration: 15 },
      { time: 25, text: 'Imagine a bright light at the center of your forehead', duration: 30 },
      { time: 55, text: 'This light represents your focused attention', duration: 20 },
      { time: 75, text: 'With each breath, the light grows brighter and clearer', duration: 30 },
      { time: 105, text: 'Feel your mind becoming sharp and alert', duration: 30 },
      { time: 135, text: 'Count your breaths from 1 to 10, then start again', duration: 120 },
      { time: 255, text: 'If you lose count, simply start over at 1', duration: 30 },
      { time: 285, text: 'Notice how your concentration is improving', duration: 30 },
      { time: 315, text: 'Your mind is becoming like a laser beam', duration: 30 },
      { time: 345, text: 'Focused, clear, and ready for any challenge', duration: 60 },
      { time: 405, text: 'Feel the energy and clarity building within you', duration: 60 },
      { time: 465, text: 'You have the power to maintain this focus', duration: 30 },
      { time: 495, text: 'Take this mental sharpness into your day', duration: 30 },
      { time: 525, text: 'Feel confident in your ability to concentrate', duration: 30 },
      { time: 555, text: 'Take three final, energizing breaths', duration: 30 },
      { time: 585, text: 'You\'re ready to tackle anything with clarity', duration: 15 },
    ],
  },
  {
    id: 'morning-motivation',
    title: 'Morning Motivation',
    description: 'Start your day with positivity',
    duration: 480, // 8 minutes
    type: 'motivation',
    backgroundSound: 'silence',
    gradientColors: ['#FFD93D', '#A8E6CF'],
    instructions: [
      { time: 0, text: 'Good morning! Today is full of possibilities', duration: 15 },
      { time: 15, text: 'Take a deep breath and feel grateful to be alive', duration: 20 },
      { time: 35, text: 'You have unique gifts to share with the world', duration: 25 },
      { time: 60, text: 'Think of three things you\'re grateful for today', duration: 30 },
      { time: 90, text: 'Feel the energy and potential within you', duration: 30 },
      { time: 120, text: 'You are capable of amazing things', duration: 20 },
      { time: 140, text: 'Every challenge is an opportunity to grow', duration: 25 },
      { time: 165, text: 'Breathe in confidence, breathe out doubt', duration: 30 },
      { time: 195, text: 'You have everything you need within you', duration: 25 },
      { time: 220, text: 'Today, you choose to be your best self', duration: 30 },
      { time: 250, text: 'Feel the warmth of self-compassion', duration: 30 },
      { time: 280, text: 'You deserve happiness and success', duration: 25 },
      { time: 305, text: 'Trust in your ability to handle whatever comes', duration: 30 },
      { time: 335, text: 'You are stronger than you know', duration: 25 },
      { time: 360, text: 'Carry this positive energy with you today', duration: 30 },
      { time: 390, text: 'You\'re going to have a wonderful day', duration: 25 },
      { time: 415, text: 'Take three deep breaths of pure possibility', duration: 30 },
      { time: 445, text: 'Step into your day with confidence and joy', duration: 20 },
      { time: 465, text: 'You\'ve got this!', duration: 15 },
    ],
  },
];

export function getSessionById(id: string): GuidedSession | undefined {
  return GUIDED_SESSIONS.find(session => session.id === id);
}

export function getSessionsByType(type: GuidedSession['type']): GuidedSession[] {
  return GUIDED_SESSIONS.filter(session => session.type === type);
}